language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
services:
 - mysql
before_script:
 - mysql -u root -e 'create database app_test'
 - mysql -u root app_test < table.sql
script: python test.py
